modLoader="javafml"
loaderVersion="[46,)"
license="GNU General Purpose License v3 (GPLv3)"

[[mods]]
modId="scalar_utils_agriculture_addon"
version="1.20-5.2.0"
displayName="Scalar Utils 5: Agriculture Addon"
logoFile="scalarutils5agriculture_addon.png"
credits="Scalar Team"
authors="Lemon_Juiced"

description='''
Fun Overpowered Agriculture That Doesn't Need To Exist In The Main Mod
'''
[[dependencies.scalar_utils_agriculture_addon]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils_agriculture_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils_agriculture_addon]]
    modId="curios"
    mandatory=true
    versionRange="[5.2.0-beta.1+1.20,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils_agriculture_addon]]
    modId="lemon_core"
    mandatory=true
    versionRange="[1.20-1.0.10,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils_agriculture_addon]]
    modId="scalar_utils"
    mandatory=true
    versionRange="[1.20-5.4.0,)"
    ordering="NONE"
    side="BOTH"