modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
modId="scalar_utils_agriculture_addon"
version="1.19.4-5.1.0"
displayName="Scalar Utils 5: Agriculture Addon"
logoFile="scalarutils5agriculture_addon.png"
credits="Scalar Team"
authors="Lemon_Juiced"

description='''
Fun Overpowered Agriculture That Doesn't Need To Exist In The Main Mod
'''
[[dependencies.scalar_utils_agriculture_addon]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils_agriculture_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils_agriculture_addon]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.4-5.1.4.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils_agriculture_addon]]
    modId="lemon_core"
    mandatory=true
    versionRange="[1.19.4-1.0.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils_agriculture_addon]]
    modId="scalar_utils"
    mandatory=true
    versionRange="[1.19.4-5.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils_agriculture_addon]]
modId="better_silicon"
    mandatory=false
    versionRange="[1.19.4-1.1.2,)"
    ordering="NONE"
    side="BOTH"